name: Benchmark MVC

on:
  workflow_dispatch:

jobs:
  ab:
    runs-on: ubuntu-22.04
    env:
      GH: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Run Benchmarks
        run: |
          cd $GITHUB_WORKSPACE/benches/ab
          chmod +x ./bench-mvc.sh ../../code/gradlew ./run-ab.sh
          ./bench-mvc.sh

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-ab-mvc-${{runner.os}}
          path: ${{ github.workspace }}/benches/ab/spring-mvc-results.log

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-ab-mvc-virtual-${{runner.os}}
          path: ${{ github.workspace }}/benches/ab/spring-mvc-virtual-results.log

  jmeter:
    runs-on: ubuntu-22.04
    env:
      GH: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup-Jmeter
        run: |
          sudo curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          sudo tar -xvf apache-jmeter-5.6.3.tgz

      - name: Run Benchmarks
        run: |
          export PATH=$GITHUB_WORKSPACE/apache-jmeter-5.6.3/bin:$PATH
          cd $GITHUB_WORKSPACE/benches/jmeter
          chmod +x ./bench-mvc.sh ../../code/gradlew ./run-jmeter.sh
          ./bench-mvc.sh

      - name: List Github workspace contents
        run: ls -lR $GITHUB_WORKSPACE

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-jmeter-mvc-${{runner.os}}
          path: ${{ github.workspace }}/benches/jmeter/spring-mvc-results.log

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-jmeter-mvc-virtual-${{runner.os}}
          path: ${{ github.workspace }}/benches/jmeter/spring-mvc-virtual-results.log
